# Site Info
title: 'DoTTak Blog'
tagline: ""
description: ''
baseurl: ""
url: https://dottak.github.io
logo: '/public/logo.png'

# Site configurations
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
permalink: pretty

paginate_path: "/page:num/"
paginate: 5

version: 1.0.0

# About/contact
author:
  name: DoTTak
  description: <strong>개발</strong>과 <strong>보안</strong>에 관심이 많습니다<br><br>새로운 지식을 배우고, 정리하면서<br>저의 <strong>성장을 기록</strong>하는 중입니다.
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/DoTTak
    # facebook:  <hide>
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:     mailto:kdw8220@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Categories:           
    - '/categories/'
    - { C 언어: '/categories/c-언어/' }
    - { Algorithm: '/categories/algorithm/' }
    - { 리버스엔지니어링: '/categories/리버스엔지니어링/' }
    - { 웹해킹: '/categories/웹해킹/' }
  Tags:
    - '/tags/'
  About:          
    - '/about/'
  # Github Project: 
  #   - 'https://github.com/DoTTak'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-100331665-2' # leave blank if you don't want google analytics
disqus_short_name: 'dottak' # leave blank if you don't want disqus
